/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BrickFrame.java
 *
 * Created on 2010-01-16, 18:48:09
 */

package brick.gui;

import brick.image.TransformsChangeNotifyer;
import brick.math.Brick;

/**
 *
 * @author Szymon
 */
public class BrickFrame extends javax.swing.JFrame {

    /** Creates new form BrickFrame */
    public BrickFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        screenDistanceScrollBar = new javax.swing.JScrollBar();
        objectDictanceScrollBar = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        xScrollersPanel = new brick.gui.ScrollersPanel();
        yScrollersPanel = new brick.gui.ScrollersPanel();
        zScrollersPanel = new brick.gui.ScrollersPanel();
        renderPanel = new brick.gui.RenderPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        screenDistanceScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        screenDistanceScrollBar.setValue(5);
        screenDistanceScrollBar.setVisibleAmount(1);
        screenDistanceScrollBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                viewChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(screenDistanceScrollBar, gridBagConstraints);

        objectDictanceScrollBar.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        objectDictanceScrollBar.setValue(5);
        objectDictanceScrollBar.setVisibleAmount(1);
        objectDictanceScrollBar.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                viewChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(objectDictanceScrollBar, gridBagConstraints);

        jLabel1.setText("Odległość matówki:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Odległość obiektu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(jLabel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.setBorder(null);

        xScrollersPanel.setAxis(TransformsChangeNotifyer.X);
        xScrollersPanel.setTitle("X");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${brick}"), xScrollersPanel, org.jdesktop.beansbinding.BeanProperty.create("abstractBrick"));
        bindingGroup.addBinding(binding);

        jTabbedPane1.addTab(xScrollersPanel.getTitle(), xScrollersPanel);

        yScrollersPanel.setAxis(TransformsChangeNotifyer.Y);
        yScrollersPanel.setTitle("Y");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${brick}"), yScrollersPanel, org.jdesktop.beansbinding.BeanProperty.create("abstractBrick"));
        bindingGroup.addBinding(binding);

        jTabbedPane1.addTab(yScrollersPanel.getTitle(), yScrollersPanel);

        zScrollersPanel.setAxis(TransformsChangeNotifyer.Z);
        zScrollersPanel.setTitle("Z");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${brick}"), zScrollersPanel, org.jdesktop.beansbinding.BeanProperty.create("abstractBrick"));
        bindingGroup.addBinding(binding);

        jTabbedPane1.addTab(zScrollersPanel.getTitle(), zScrollersPanel);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.EAST);

        renderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        renderPanel.setBrick(getBrick());

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, this, org.jdesktop.beansbinding.ELProperty.create("${brick}"), renderPanel, org.jdesktop.beansbinding.BeanProperty.create("brick"));
        bindingGroup.addBinding(binding);

        getContentPane().add(renderPanel, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void viewChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_viewChanged
		brick.setBrickDistance(objectDictanceScrollBar.getValue());
		brick.setScreenDistance(screenDistanceScrollBar.getValue());
		brick.recalc();
		renderPanel.repaint();
	}//GEN-LAST:event_viewChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrickFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollBar objectDictanceScrollBar;
    private brick.gui.RenderPanel renderPanel;
    private javax.swing.JScrollBar screenDistanceScrollBar;
    private brick.gui.ScrollersPanel xScrollersPanel;
    private brick.gui.ScrollersPanel yScrollersPanel;
    private brick.gui.ScrollersPanel zScrollersPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

	private Brick brick = new Brick();

	/**
	 * Get the value of brick
	 *
	 * @return the value of brick
	 */
	public Brick getBrick() {
		return brick;
	}

	/**
	 * Set the value of brick
	 *
	 * @param brick new value of brick
	 */
	public void setBrick(Brick brick) {
		this.brick = brick;
	}
//	private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);
//
//	/**
//	 * Add PropertyChangeListener.
//	 *
//	 * @param listener
//	 */
//	@Override
//	public void addPropertyChangeListener(PropertyChangeListener listener) {
//		propertyChangeSupport.addPropertyChangeListener(listener);
//	}
//
//	/**
//	 * Remove PropertyChangeListener.
//	 *
//	 * @param listener
//	 */
//	@Override
//	public void removePropertyChangeListener(PropertyChangeListener listener) {
//		propertyChangeSupport.removePropertyChangeListener(listener);
//	}

}
